### ISSUE TITLE
TODO-list documents

### ISSUE THREAD

**Issue by seirl** [prologin/concours-site#77]
> ###### Originally posted 2016-05-30 10:30 by [serialk](https://bitbucket.org/serialk/) on Bitbucket

* [x] Add a tshirt size column on the final attendance sheet
* [ ] ~EPTV contract~
* [ ] ~Ephemere contract~
* [x] Organizers badges generation (waiting for @bifore PR)
* [x] Lunch tickets generation (waiting for @bifore PR)
* [ ] ~Bill generation for sponsors~
* [ ] Reorganize the finals documents into categories

**Comment by zopieux** [comment]
> ###### Originally posted 2016-06-09 19:13 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

Added tshirt size column for attendance sheet

**Comment by seirl** [comment]
I don't think the contracts should be generated on the website. I think we can close this issue.

**Comment by seirl** [comment]
Actually there is still one item on the list left.

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/issues/77
